### ISSUE TITLE
Footer is still buggy and not working as intended

### ISSUE THREAD

**Issue by P0LAN** [P0LAN/main#2]
Hello, I couldn't make the footer work with our grid 
@mrmacaroni2  should fix that because he knows better than me about this spaghetti code
Todo:

> **_make a proper footer_ (Updated)**

> **_Fix navbar_ (Fixed)**

> **_Add proper content(sections)_**

Cheers 
Dineo

**Comment by mrmacaroni2** [comment]
**im done**  :)
